language: elixir
matrix:
  include:
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.7
      otp_release: 21.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
